# Generated by Django 6.0.6 on 2026-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=200)),
                ('callsign', models.CharField(max_length=100)),
                ('captain_name', models.CharField(max_length=200)),
                ('cargo_items', models.JSONField()),
                ('passengers', models.JSONField()),
                ('biohazard_level', models.IntegerField()),
                ('chemical_hazard_level', models.IntegerField()),
                ('security_hazard_level', models.IntegerField()),
                ('recommendation', models.TextField()),
                ('medical_status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('hazmat_status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('security_status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
