# Generated by Django 6.0.6 on 2026-06-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_shipassessment_biohazard_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipassessment',
            name='biohazard_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipassessment',
            name='chemical_hazard_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipassessment',
            name='security_hazard_level',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='shipassessment',
            constraint=models.CheckConstraint(condition=models.Q(('biohazard_level__range', (0, 10))), name='biohazard_level_range'),
        ),
        migrations.AddConstraint(
            model_name='shipassessment',
            constraint=models.CheckConstraint(condition=models.Q(('chemical_hazard_level__range', (0, 10))), name='chemical_hazard_level_range'),
        ),
        migrations.AddConstraint(
            model_name='shipassessment',
            constraint=models.CheckConstraint(condition=models.Q(('security_hazard_level__range', (0, 10))), name='security_hazard_level_range'),
        ),
    ]
