# Generated by Django 6.0.6 on 2026-06-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_shipassessment_biohazard_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipassessment',
            name='inappropriate_content',
            field=models.BooleanField(default=False),
        ),
    ]
